# frozen_string_literal: true

source "https://rubygems.org"
gemspec
gem 'jekyll-admin', group: :jekyll_plugins
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'

group :jekyll_plugins do
    gem 'octopress-minify-html'
end
